import {
  InputTextModal,
  InputPasswordModal,
  InputNumberEditModal,
  InputTextareaModal,
  SelectEditModal,
  DatePickerEditModal,
  TimePickerEditModal,
  RangePickerEditModal,
  CheckboxEditModal,
  CheckboxGroupEditModal,
  RadioGroupEditModal,
  SwitchEditModal,
  UploadEditModal,
  SliderEditModal,
  RateEditModal,
  CascaderEditModal,
  TreeSelectEditModal,
  MentionsEditModal,
  AutoCompleteEditModal,
  TransferEditModal,
  StepsEditModal,
  ColorPickerEditModal,
  SearchEditModal,
  SubmitEditModal,
  TourEditModal,
  SegmentedEditModal,
  FloatButtonEditModal,
  WatermarkEditModal,
} from "@/components/modals";

import { InputType } from "./getInputType";

export const modalMap: Record<InputType, React.ComponentType<any> | null> = {
  text: InputTextModal,
  password: InputPasswordModal,
  inputnumber: InputNumberEditModal,
  textarea: InputTextareaModal,
  select: SelectEditModal,
  datepicker: DatePickerEditModal,
  timepicker: TimePickerEditModal,
  rangepicker: RangePickerEditModal,
  checkbox: CheckboxEditModal,
  checkboxgroup: CheckboxGroupEditModal,
  radiogroup: RadioGroupEditModal,
  switch: SwitchEditModal,
  upload: UploadEditModal,
  slider: SliderEditModal,
  rate: RateEditModal,
  cascader: CascaderEditModal,
  treeselect: TreeSelectEditModal,
  mentions: MentionsEditModal,
  autocomplete: AutoCompleteEditModal,
  transfer: TransferEditModal,
  search: SearchEditModal,
  submit: SubmitEditModal,
  steps: StepsEditModal,
  colorpicker: ColorPickerEditModal,
  tour: TourEditModal,
  segmented: SegmentedEditModal,
  floatbutton: FloatButtonEditModal,
  watermark: WatermarkEditModal,
  other: null,
};
